---
apiVersion: source.toolkit.fluxcd.io/v1alpha1
kind: GitRepository
metadata:
  creationTimestamp: null
  name: gotk-system
  namespace: gitops-system
spec:
  interval: 1m0s
  ref:
    branch: master
  url: https://github.com/chanwit/multi-env
status: {}

